source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 4.0', '>= 4.0.0'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 2.7.1'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '>= 4.0.0'
# Use jquery as the JavaScript library
gem 'jquery-rails', '>= 3.1.3'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'jbuilder', '~> 2.0'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'rspec-rails', '>= 3.3.3'
  gem 'ruby-debug-ide'
  gem 'valid_attribute'
  gem 'capybara'
  gem 'capybara-webkit', '>= 1.6.0'
  gem 'selenium-webdriver'
  gem 'factory_girl_rails', '>= 4.5.0'
  gem 'launchy'
  gem 'database_cleaner'
  gem 'rb-fsevent', '~> 0.9.1'
  gem 'guard-rspec'
end

gem 'mongoid'
gem 'cloudinary', '~> 1.1'
gem 'attachinary', :path => '../..'
gem 'simple_form'

